### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by avvj** [lucashowardmiller/the_knowledge#2]
I'm getting the below error when running it with the parameters used in the README screenshot.

`Enter a search: reddit
Use the knowledge panel from: imgur
Hide search (y/n): y
Traceback (most recent call last):
  File "the_knowledge.py", line 71, in <module>
    main()
  File "the_knowledge.py", line 32, in main
    + '&' + get_knowledge_panel(knowledge_panel_search) + '&' + KP_ONLY
  File "the_knowledge.py", line 44, in get_knowledge_panel
    search_box = driver.find_element_by_xpath('/html/body/div/div[3]/form/div[2]/div/div[1]/div/div[1]/input')
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div/div[3]/form/div[2]/div/div[1]/div/div[1]/input
`

**Comment by lucashowardmiller** [comment]
If a page takes longer than 2 seconds to load selenium will error out like that. This is my second script that uses selenium so, I'm still learning how to use the feature in selenium that lets you wait to see if an element loaded. 

As a temp workaround you can increase the two waits in the main part of the script, or use faster internet as a workaround. 

In the coming days, I'll probably be able to fix this. I'd also accept any pull requests to fix this, or anything really.

**Comment by lucashowardmiller** [comment]
This should be fixed in the new version. I added an implicit wait that allows up for 10 seconds for each element to load.
